In [8]:
import numpy as np

In [5]:
def matrix_factorization(R, P, Q, K=2, steps=5000, alpha=0.0002, beta=0.02, tol=0.001):
    n, m = R.shape
    Q = Q.T
    for _ in range(steps):
        for i in range(n):
            for j in range(m):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:], Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P, Q)
        e = 0
        for i in range(n):
            for j in range(m):
                if R[i][j] > 0:
                    e = e + (R[i][j] - np.dot(P[i,:], Q[:,j])) ** 2
                    for k in range(K):
                        e = e + (beta/2) * (P[i][k] ** 2 + Q[k][j] ** 2) # total error
        if e < tol:
            break
    return P, Q.T

In [60]:
R = np.array([[4,0,2,4],  # user 1
              [4,0,2,0],  # user 2
              [5,2,0,1],  # user 3
              [1,0,0,5],  # user 4
              [2,3,0,5]]) # user 5

In [61]:
n, m = R.shape
K = 2 # latent variable

P = np.random.rand(n, K) # randomly create P, Q first
Q = np.random.rand(m, K)
P, Q = matrix_factorization(R, P, Q, K)
Rhat = np.dot(P, Q.T)

In [62]:
np.set_printoptions(precision=2)
print(Rhat)

[[ 3.96  3.08  2.1   3.96]
 [ 4.01  2.82  1.9   3.36]
 [ 4.96  2.    1.25  1.01]
 [ 1.    2.66  1.91  4.98]
 [ 2.01  2.97  2.1   5.  ]]


In [16]:
type (Rhat)

numpy.ndarray

In [63]:
R

array([[4, 0, 2, 4],
       [4, 0, 2, 0],
       [5, 2, 0, 1],
       [1, 0, 0, 5],
       [2, 3, 0, 5]])

In [64]:
P

array([[ 1.61,  1.05],
       [ 1.62,  0.8 ],
       [ 1.96, -0.29],
       [ 0.46,  1.89],
       [ 0.86,  1.75]])

In [65]:
Q.T

array([[ 2.51,  1.19,  0.76,  0.87],
       [-0.08,  1.12,  0.83,  2.43]])